DOR-4303: Refactor swagger item handling
zalora/bee pull request #28
Opened 2023-04-04 03:24 UTC by adirizka7

2023-04-05 09:26 UTC, yessypp requested changes
Left 1 question, otherwise looks fine.

2023-04-05 09:47 UTC, adirizka7 commented on g_docs.go
> +func enrichSwaggerItem(item *swagger.Item, opts swagger.Operation, httpMethod string) *swagger.Item {
Great catch! Removed in https://github.com/zalora/bee/pull/28/commits/0f64497665d76e3c52bf0d1c01fa88d44da8a88c

2023-04-05 13:55 UTC, fahimbagar approved these changes

2023-04-06 09:19 UTC, yessypp approved these changes

2023-04-06 17:49 UTC, merged