DOR 3202 - Fix Error in Swagger API Doc
zalora/bee pull request #8
Opened 2021-06-30 01:44 UTC by adirizka7

This PR does:
- add support for formData type with @Accept form comment
- add support for nested packages definition, eg. ZDAProduct.Product

2021-08-02 03:57 UTC, fraenky8 requested changes
Left some notes.

But this PR is huge and I didn't read through all the code & changes - mainly I dont understand in detail whats going on. Wondering if this PR can be broken down to multiple PRs?

- Adding enum.
- Refactoring
- ...

Also since we rely on this tool, we need to be very careful to not break anything we dont understand nor introduce more complexity it already has. Once you refactor it, your name will show up on the latest changes for the code, and the saying goes: Once you touch it, you own it.

2021-08-02 03:57 UTC, fraenky8 commented on go.sum
> +github.com/davecgh/go-spew v1.1.0/go.mod h1:J7Y8YcW2NihsgmVo/mv3lAwl/skON4iLHjSsI+c5H38=
I see this is not used anywhere - is this a leftover from local testing?

When on master branch and running a `go mod tidy && go mod vendor` it does not change anything (go 1.16.6).

Bringing this up to reduce the size of the PR a bit. Something to consider on every ticket we are working on: The reviewer has to go through all the changes - the bigger the change-set the higher the chance to miss something (important). We aim for small PRs with single responsibility.

2021-08-02 03:57 UTC, fraenky8 commented on g_docs.go
> +				enrichItem(replicatedItem, tag, route)
Wondering if this is really necessary? 🤔 Can we just pass a non-pointer to enrich and return a new, enriched swagger-item?

Also I quite dont understand the comment above. Does it mean two endpoints might share the same controller?

2021-08-02 03:57 UTC, fraenky8 commented on g_docs.go
> +				res := new(objectResource)
Whats that? I dont see `rest` is used beside here? What does it do and why it's important to parse and throw away?

*Edit* I see `parseObject()` exits the run. Lets return the error and exit here in the for-loop to make it obvious whats happeneing?

2021-08-02 03:57 UTC, fraenky8 commented on g_docs.go
> +func (res *objectResource) parseObject() {
Nitpicking here but now this is a method instead of a function, we could simply name it `parse` (and return an error as per previous comment)

2021-08-02 03:57 UTC, fraenky8 commented on g_docs.go
> +		return
One comment on [naked returns](https://github.com/golang/go/wiki/CodeReviewComments#named-result-parameters).

> Naked returns are okay if the function is a handful of lines. Once it's a medium sized function, be explicit with your return values. 

In general (but we dont have a clear guideline on this) we prefer no naked returns at all. We make exception tho as the example given in the link: when there are multiple return parameters of the same type.

This also applies to all other functions/methods here.

2021-08-02 03:57 UTC, fraenky8 commented on g_docs.go
> +	value = strings.Replace(value, "/", ".", -1)
Lets use `strings.ReplaceAll` here.

2021-08-02 03:57 UTC, fraenky8 commented on g_docs.go
> +	var name string
A variable should be declared as close where it is used - line 1123 in this case.

2021-09-03 04:55 UTC, adirizka7 commented
Closing this PR since it is being broken down to multiple small PRs. Subtasks can be found in the DOR-3202 ticket.

2021-09-03 04:55 UTC, closed without merging